/**
 * Maps DummyJSON todos to calendar events.
 *
 * DummyJSON has no events, so start/end are derived from the todo id with a
 * fixed arithmetic rule (no randomness, no "now"): the same todo always lands
 * on the same slot relative to the seed anchor, so seeds never move after a
 * refresh or a re-seed. The anchor (Monday of the week the calendar was first
 * seeded) is persisted with the data.
 */
import { EVENT_COLORS, type CalendarEvent, type EventColor, type RecurrenceRule } from './types';
import { addDays, startOfWeek, type DateKey } from './time/dateKey';
import { zonedToUtc } from './time/zoned';
import { toIso } from './changes';

export interface Todo {
  id: number;
  todo: string;
  completed: boolean;
  userId: number;
}

const WEEKS_BEFORE_ANCHOR = 3;
const WEEKS_SPREAD = 10;
const DURATIONS = [30, 45, 60, 90, 60, 120];
const PALETTE: EventColor[] = EVENT_COLORS.filter((c) => c !== 'slate');

/** Users 1-30 are the ones preloaded by the attendee picker. */
const ATTENDEE_POOL = 30;

const RECURRING_RULES: RecurrenceRule[] = [
  { freq: 'weekly', interval: 1, end: { type: 'never' } },
  { freq: 'daily', interval: 1, end: { type: 'count', count: 10 } },
  { freq: 'weekly', interval: 1, byWeekday: [1, 3, 5], end: { type: 'count', count: 12 } },
  { freq: 'monthly', interval: 1, monthlyMode: 'nthWeekday', end: { type: 'never' } },
  { freq: 'monthly', interval: 1, monthlyMode: 'dayOfMonth', end: { type: 'count', count: 6 } },
  { freq: 'weekly', interval: 2, end: { type: 'never' } },
];

export function seedAnchorFor(today: DateKey): DateKey {
  return startOfWeek(today, 1);
}

export function todoToEvent(todo: Todo, anchor: DateKey, timeZone: string, now: string): CalendarEvent {
  const id = todo.id;
  const firstMonday = addDays(anchor, -7 * WEEKS_BEFORE_ANCHOR);
  // 37 is coprime with 50, so ids spread evenly over the 50 weekdays of 10 weeks.
  const slot = (id * 37) % (WEEKS_SPREAD * 5);
  const day = addDays(firstMonday, Math.floor(slot / 5) * 7 + (slot % 5));
  const startMinutes = (8 + ((id * 13) % 10)) * 60 + ((id * 7) % 4) * 15; // 08:00-17:45 on 15-min steps
  const start = zonedToUtc(day, startMinutes, timeZone);
  const end = start + DURATIONS[id % DURATIONS.length] * 60_000;

  const attendeeIds = [...new Set([1 + ((id * 7) % ATTENDEE_POOL), ...(id % 3 === 0 ? [1 + ((id * 11) % ATTENDEE_POOL)] : [])])]
    .filter((attendee) => attendee !== todo.userId);

  const recurrence = id % 40 === 0 ? RECURRING_RULES[(id / 40 - 1) % RECURRING_RULES.length] : null;

  return {
    id: `todo-${id}`,
    title: todo.todo,
    description: `Imported from DummyJSON todo #${id}${todo.completed ? ' (marked completed)' : ''}.`,
    start: toIso(start),
    end: toIso(end),
    allDay: false,
    timeZone,
    organizerId: todo.userId,
    attendeeIds,
    reminderMinutes: id % 5 === 0 ? 10 : null,
    color: todo.completed ? 'slate' : PALETTE[todo.userId % PALETTE.length],
    recurrence,
    exdates: [],
    recurringEventId: null,
    originalStart: null,
    remoteId: id,
    createdAt: now,
    updatedAt: now,
  };
}

/** Deterministic PRNG (mulberry32) so stress data is reproducible. */
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Generates `count` local-only events around `anchor` for the performance demo. */
export function generateStressEvents(count: number, anchor: DateKey, timeZone: string, now: string): CalendarEvent[] {
  const random = mulberry32(count * 7919);
  return Array.from({ length: count }, (_, i) => {
    const day = addDays(startOfWeek(anchor, 1), Math.floor(random() * 35) - 7);
    const minutes = (7 + Math.floor(random() * 12)) * 60 + Math.floor(random() * 4) * 15;
    const start = zonedToUtc(day, minutes, timeZone);
    const duration = (1 + Math.floor(random() * 8)) * 15;
    return {
      id: `stress-${i}`,
      title: `Load test #${i + 1}`,
      description: 'Generated by the performance demo.',
      start: toIso(start),
      end: toIso(start + duration * 60_000),
      allDay: false,
      timeZone,
      organizerId: 1 + Math.floor(random() * ATTENDEE_POOL),
      attendeeIds: [1 + Math.floor(random() * ATTENDEE_POOL)],
      reminderMinutes: null,
      color: PALETTE[i % PALETTE.length],
      recurrence: null,
      exdates: [],
      recurringEventId: null,
      originalStart: null,
      remoteId: null,
      createdAt: now,
      updatedAt: now,
    };
  });
}
