/**
 * Core domain model.
 *
 * Times are stored as ISO-8601 UTC instants ("2026-10-05T03:30:00.000Z").
 * The zone the user *picked* is only used for display, except `timeZone` on an
 * event: recurring events repeat at the same wall-clock time in that zone,
 * which is what keeps a "9:00 every day" meeting at 9:00 across DST changes.
 */

/** 0 = Sunday ... 6 = Saturday (Date#getDay convention). */
export type Weekday = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly';

/**
 * Monthly rules derive their day from the series start date, like Google Calendar:
 *  - dayOfMonth:  "Monthly on day 31"   (clamped to the last day in shorter months)
 *  - nthWeekday:  "Monthly on the 2nd Tuesday" (skips months without a 5th weekday)
 *  - lastWeekday: "Monthly on the last Friday"
 */
export type MonthlyMode = 'dayOfMonth' | 'nthWeekday' | 'lastWeekday';

export type RecurrenceEnd =
  | { type: 'never' }
  /** Inclusive last date, as a calendar date in the event's zone. */
  | { type: 'until'; until: string }
  | { type: 'count'; count: number };

export interface RecurrenceRule {
  freq: RecurrenceFrequency;
  /** Every N days / weeks / months. */
  interval: number;
  /** Weekly only. */
  byWeekday?: Weekday[];
  /** Monthly only. */
  monthlyMode?: MonthlyMode;
  end: RecurrenceEnd;
}

export const EVENT_COLORS = ['indigo', 'sky', 'emerald', 'amber', 'rose', 'violet', 'slate'] as const;
export type EventColor = (typeof EVENT_COLORS)[number];

export interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  /** ISO UTC instant. For all-day events: UTC midnight of the first day (a "floating" date). */
  start: string;
  /** ISO UTC instant, exclusive. For all-day events: UTC midnight of the day after the last day. */
  end: string;
  allDay: boolean;
  /** IANA zone the event was scheduled in; recurrences expand in this zone's wall-clock time. */
  timeZone: string;
  organizerId: number;
  attendeeIds: number[];
  /** Minutes before start, or null for no reminder. */
  reminderMinutes: number | null;
  color: EventColor;
  recurrence: RecurrenceRule | null;
  /** Original starts (ISO) of series occurrences that were deleted or replaced by an override. */
  exdates: string[];
  /** Set on a single-occurrence override ("this event" edits): the series it belongs to. */
  recurringEventId: string | null;
  /** Set on overrides: the original start (ISO) of the occurrence it replaces. */
  originalStart: string | null;
  /** DummyJSON todo id for seeded events; null for events created in this app. */
  remoteId: number | null;
  createdAt: string;
  updatedAt: string;
}

export type EventsById = Record<string, CalendarEvent>;

/** One concrete, drawable instance of an event inside the visible range. */
export interface Occurrence {
  /** Stable id used in URLs: the event id, or `${seriesId}~${originalStartMs}` for series instances. */
  key: string;
  /** The stored record this occurrence came from (master for series instances). */
  event: CalendarEvent;
  /** Master series id when the occurrence belongs to a recurring series, else null. */
  seriesId: string | null;
  /** Start as generated by the rule (differs from `start` for moved overrides). */
  originalStart: number;
  start: number;
  end: number;
  allDay: boolean;
  /** True for virtual instances generated from a master's rule. */
  isInstance: boolean;
}

/** Values edited in the event form or produced by a drag. Times are UTC ms. */
export interface EventDraft {
  title: string;
  description: string;
  start: number;
  end: number;
  allDay: boolean;
  timeZone: string;
  attendeeIds: number[];
  reminderMinutes: number | null;
  color: EventColor;
  recurrence: RecurrenceRule | null;
}

export type EditScope = 'this' | 'following' | 'all';

export interface User {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  image: string;
  username?: string;
  phone?: string;
  company?: { name?: string; title?: string; department?: string };
}

export interface AuthUser extends User {
  username: string;
}
